version: '3.1'
services:
  spring-homework-docker:
    image: spring-homework-docker
    container_name: spring-homework-docker 
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=newuser
      - POSTGRES_DB=test
